module.exports = [
	// BAR SNACKS //
	{
		name: 'Hand Cut French Fries',
		img: 'https://images2.imgbox.com/e9/6c/UzREwvLs_o.jpeg',
		cost: 6,
		costString: '$6.00',
		description: 'Add: cheese $1 - cheese & gravy $2 - chili & cheese $3',
		category: 'bar-snack',
	},
	{
		name: 'Onion Rings',
		img: '',
		cost: 9,
		costString: '$9.00',
		description: 'Fried crisp, served with dipping sauce',
		category: 'bar-snack',
	},
	{
		name: 'Chili With the "Works"',
		img: '',
		cost: 10,
		costString: '$10.00',
		description: 'Chili',
		category: 'bar-snack',
	},
	{
		name: 'Mozzarella Sticks',
		img: '',
		cost: 9,
		costString: '$9.00',
		description: 'Served with marinara sauce',
		category: 'bar-snack',
	},
	{
		name: 'Pizza Napolitano',
		img: '',
		cost: 16,
		costString: '$16.00',
		description: 'Handmade pizza',
		category: 'bar-snack',
	},
	{
		name: 'Pizza Parma',
		img: '',
		cost: 20,
		costString: '$20.00',
		description: 'Mozzarella, prosciutto, & arugula',
		category: 'bar-snack',
	},
	{
		name: 'Chicken Tenders Basket w/Fries',
		img: '',
		cost: 12.5,
		costString: '$12.50',
		description: 'Served with honey mustard',
		category: 'bar-snack',
	},
	{
		name: 'Fish & Chips',
		img: '',
		cost: 16,
		costString: '$16.00',
		description: 'Fish with chips',
		category: 'bar-snack',
	},
	// WINGS //
	{
		name: '10 Dino\'s Famous Fat Wings',
		img: 'https://images2.imgbox.com/c3/c4/ymLV3mBa_o.jpg',
		cost: 16,
		costString: '$16.00',
		description: 'Traditional buffalo, Mild, Hot, Atomic, Thai Chili, BBQ, Teriyaki, Koream BBQ, Garlic Parm (Add $2), Honey Garlic (Add $2)',
		category: 'wings',
	},
	{
		name: '20 Dino\'s Famous Fat Wings',
		img: 'https://images2.imgbox.com/c3/c4/ymLV3mBa_o.jpg',
		cost: 30,
		costString: '$30.00',
		description: 'Traditional buffalo, Mild, Hot, Atomic, Thai Chili, BBQ, Teriyaki, Koream BBQ, Garlic Parm (Add $2), Honey Garlic (Add $2)',
		category: 'wings',
	},
	{
		name: 'Boneless Wings',
		img: 'https://images2.imgbox.com/c3/c4/ymLV3mBa_o.jpg',
		cost: 15,
		costString: '$15.00',
		description: 'Traditional buffalo, Mild, Hot, Atomic, Thai Chili, BBQ, Teriyaki, Koream BBQ, Garlic Parm (Add $2), Honey Garlic (Add $2)',
		category: 'wings',
	},
	// BURGERS //
	{
		name: '8oz Pat LaFreida Burger',
		img: 'https://images2.imgbox.com/cb/93/D8q8p2GT_o.jpg',
		cost: 15,
		costString: '$15.00',
		description: 'All our burgers are servered with hand cut fries & a pickle. Add: cheese (Swiss, American, Provolone, Cheddar, Crumbled blue cheese, Mozzarella, Pepper jack). Addtional: Lettuce, Tomato, Raw Onions, Caramelized onions (Add $1), Sauteed mushrooms (Add $1), Hot cherry peppers (Add $1), Bacon (Add $1.50), Avocado (Add $1.50)',
		category: 'burger',
	},
	{
		name: 'Dino\'s Famous Sliders',
		img: '',
		cost: 14,
		costString: '$14.00',
		description: '3 sliders with American cheese and grilled onions',
		category: 'burger',
	},
	{
		name: 'Dean Martin Burger',
		img: '',
		cost: 18,
		costString: '$18.00',
		description: 'Applewood smoked bacon, chedder cheese, sauteed muchrooms, drizzled with white truffle oil',
		category: 'burger',
	},
	{
		name: 'California Burger',
		img: 'https://images2.imgbox.com/ae/e6/xlYuj6z7_o.jpg',
		cost: 18,
		costString: '$18.00',
		description: 'Avocado, pepper jack cheese lettuce, tomato, and ranch dressing',
		category: 'burger',
	},
	{
		name: 'Western Burger',
		img: 'https://images2.imgbox.com/3c/b2/30ZURsrn_o.jpg',
		cost: 18,
		costString: '$18.00',
		description: 'Applewood smoked bacon, cheddar cheese, onion rings, and tangy BBQ sauce',
		category: 'burger',
	},
	{
		name: 'Black Bean Veggie Burger',
		img: '',
		cost: 16,
		costString: '$16.00',
		description: 'Avocado, lettuce, tomato & garlic aioli',
		category: 'burger',
	},
	// SALAD //
	{
		name: 'Kale Ceasar Salad',
		img: 'https://images2.imgbox.com/14/f7/7MegnUg5_o.jpg',
		cost: 14,
		costString: '$14.00',
		description: 'Kale leaves tossed in a creamy Caesar dressing with croutons & parmesan cheese. Add: Chicken $4, Grilled Shrimp $6, Steak $7',
		category: 'salad',
	},
	{
		name: 'Mermaid Salad',
		img: 'https://images2.imgbox.com/bd/92/6rUWWZ64_o.jpg',
		cost: 20,
		costString: '$20.00',
		description: 'Pan seared sesame crusted ahi tuna served over greens & wasabi ginger soy sauce',
		category: 'salad',
	},
	// SANDWICHES //
	{
		name: 'Dino\'s Cheesesteak',
		img: '',
		cost: 16,
		costString: '$16.00',
		description: 'Freshly sliced ribeye with grilled onions, sauteed mushrooms & provolone cheese served on ciabatta bread',
		category: 'sandwich',
	},
	{
		name: 'Turkey or Chicken Club',
		img: '',
		cost: 14,
		costString: '$14.00',
		description: 'Fresh turkey or chicken, lettuce, tomato, bacon, & mayo',
		category: 'sandwich',
	},
	{
		name: 'Panino Parma ',
		img: 'https://images2.imgbox.com/7d/ae/171fnJAp_o.jpg',
		cost: 16,
		costString: '$16.00',
		description: 'Prosciutto, mozzarella, arugula, cherry tomatoes',
		category: 'sandwich',
	},
	// ENTREE //
	{
		name: 'Surf and Turf',
		img: '',
		cost: 32,
		costString: '$32.00',
		description: 'Filet mignon & shrimp. Substitute: Lobster Tail $15, Scallops $12',
		category: 'entree',
	},
	{
		name: 'Seasonal Steak',
		img: 'https://images2.imgbox.com/80/4c/SQd9l4fz_o.jpg',
		cost: 24,
		costString: '$24.00',
		description: 'Marinated & Served with potatoes & vegetables',
		category: 'entree',
	},
	
]