module.exports = [
	{
		name: 'Buffalo Wings',
		cost: 10.0,
		img: '',
		costString: '$10.00',
		description: 'Mild, Medium, Hot, Atomic, Teriyaki, BBQ, Thai',
		cateogy: 'appetizer',
	},
	{
		name: 'Chicken Fingers',
		cost: 9.5,
		img: '',
		costString: '$9.50',
		description: 'Served with honey mustard.',
		cateogy: 'appetizer',
	},
	{
		name: 'Mozzarella Sticks',
		cost: 8.5,
		img: '',
		costString: '$8.5',
		description: 'Served with marinara sauce',
		cateogy: 'appetizer',
	},
	{
		name: 'Jalepeno Poppers',
		cost: 8.0,
		img: '',
		costString: '$8.00',
		description: 'Served with horseradish sauce',
		cateogy: 'appetizer',
	},
	{
		name: 'Dino\'s Mac & Cheese',
		cost: 9.0,
		img: '',
		costString: '$9.00',
		description: 'Classic Mac & Cheese. Add bacon $2',
		cateogy: 'appetizer',
	},
	{
		name: 'Onion Rings',
		cost: 6.00,
		img: '',
		costString: '$6.00',
		description: 'Fried crisp, served with dipping sauce',
		cateogy: 'appetizer',
	},
	{
		name: 'Hand Cut French Fries',
		cost: 5.00,
		img: '',
		costString: '$5.00',
		description: 'w/cheese $6, w/cheese & gravy $7, w/chili & cheese $8, w/gravy & mozzarella',
		cateogy: 'appetizer',
	},
	{
		name: 'House Salad',
		cost: 9.00,
		img: '',
		costString: '$9.00',
		description: 'Large salad, with fresh seasonal greens, veggies & house dressing. w/chicken $4',
		cateogy: 'salad',
	},
	{
		name: 'Traditional Caesar Salad',
		cost: 9.00,
		img: '',
		costString: '$9.00',
		description: 'w/chicken $4',
		cateogy: 'salad',
	},
	{
		name: 'Insalata Italiana',
		cost: 11.00,
		img: '',
		costString: '$11.00',
		description: 'Fresh mozzarella, roasted peppers, tomato, basil, topped with balsamic vinegar',
		cateogy: 'salad',
	},
	{
		name: 'Roast Beef',
		cost: 11.00,
		img: '',
		costString: '$11.00',
		description: 'Fresh mozzarella, tomato, roasted peppers, balsamic vinegar. Served with hand cut fries.',
		cateogy: 'sandwich',
	},
	{
		name: 'Chicken Supreme',
		cost: 11.00,
		img: '',
		costString: '$11.00',
		description: 'Fresh mozzarella, tomato, roasted peppers, balsamic vinegar. Served with hand cut fries.',
		cateogy: 'sandwich',
	},
	{
		name: 'French Dip',
		cost: 10.00,
		img: '',
		costString: '$10.00',
		description: 'Tender roast beef sandwich, dipped in au jus. Served with hand cut fries.',
		cateogy: 'sandwich',
	},
	{
		name: 'Pastrami Melt',
		cost: 10.00,
		img: '',
		costString: '$10.00',
		description: 'Hot pastrami & cheese on rye bread. Served with hand cut fries.',
		cateogy: 'sandwich',
	},
	{
		name: 'Reuben Sandwich',
		cost: 7.79,
		img: '',
		costString: '$7.79',
		description: 'Pastrami, with sauerkraut, Russian dressing, on rye bread. Served with hand cut fries.',
		cateogy: 'sandwich',
	},
	{
		name: 'Turkey Club',
		cost: 10.5,
		img: '',
		costString: '$10.50',
		description: '(traditional or wrap) with bacon, lettuce, tomato, mayo',
		cateogy: 'sandwich',
	},
	{
		name: 'BLT',
		cost: 8.50,
		img: '',
		costString: '$8.5',
		description: 'Classic bacon, lettuce, tomato sandwich. w/avocado $1.50',
		cateogy: 'sandwich',
	},
]