module.exports = [
	// BAR SNACKS //
	{
		name: 'Hand Cut French Fries',
		cost: 6.0,
		img: '',
		costString: '$6.00',
		description: 'w/cheese Add $1, w/cheese & gravy Add $2, w/chili & cheese $8, w/gravy & mozzarella',
		category: 'bar-snack',
	},
	{
		name: 'Onion Rings',
		cost: 9.0,
		img: '',
		costString: '$9.00',
		description: 'Fried crisp, served with dipping sauce',
		category: 'bar-snack',
	},
	{
		name: 'Chili With the Works',
		cost: 10.0,
		img: '',
		costString: '$10.00',
		description: 'Chili',
		category: 'bar-snack',
	},
	{
		name: 'Mozzarella Sticks',
		cost: 9,
		img: '',
		costString: '$9',
		description: 'Served with marinara sauce',
		category: 'bar-snack',
	},
	{
		name: 'Pizza Napolitano',
		cost: 16.0,
		img: '',
		costString: '$16.00',
		description: 'Handmade pizza',
		category: 'bar-snack',
	},
	{
		name: 'Pizza Parma',
		cost: 20.0,
		img: '',
		costString: '$20.00',
		description: 'Handmade pizza',
		category: 'bar-snack',
	},
	{
		name: 'Chicken Tenders Basket w/Fries',
		cost: 9.5,
		img: '',
		costString: '$9.50',
		description: 'Served with honey mustard',
		category: 'bar-snack',
	},
	// WINGS //
	{
		name: '10 Dino\'s Famous Fat Wings',
		cost: 16.0,
		img: '',
		costString: '$16.00',
		description: 'Mild, Medium, Hot, Atomic, Teriyaki, BBQ, Thai',
		category: 'wings',
	},
	{
		name: '30 Dino\'s Famous Fat Wings',
		cost: 20.0,
		img: '',
		costString: '$20.00',
		description: 'Mild, Medium, Hot, Atomic, Teriyaki, BBQ, Thai',
		category: 'wings',
	},
	{
		name: '10 Boneless Wings',
		cost: 15.0,
		img: '',
		costString: '$15.00',
		description: 'Mild, Medium, Hot, Atomic, Teriyaki, BBQ, Thai',
		category: 'wings',
	},
	// BURGERS //
	{
		name: '8oz Pat LaFreida Burger',
		cost: 15.0,
		img: '',
		costString: '$15.00',
		description: 'All our burgers are servered with hand cut fries & a pickle',
		category: 'burger',
	},
	{
		name: 'Dino\'s Famous Sliders',
		cost: 14.0,
		img: '',
		costString: '$14.00',
		description: '3 sliders with American cheese and grilled onions',
		category: 'burger',
	},
	{
		name: 'Dean Martin Burger',
		cost: 18.0,
		img: '',
		costString: '$18.00',
		description: 'Applewood smoked bacon, chedder cheese, sauteed muchrooms, drizzled with white truffle oil',
		category: 'burger',
	},
	{
		name: 'California Burger',
		cost: 18.0,
		img: '',
		costString: '$18.00',
		description: 'Avocado, pepper jack cheese lettuce, tomato, and ranch dressing',
		category: 'burger',
	},
	{
		name: 'Western Burger',
		cost: 18.0,
		img: '',
		costString: '$18.00',
		description: 'Applewood smoked bacon, cheddar cheese, onion rings, and tangy BBQ sauce',
		category: 'burger',
	},
	{
		name: 'Black Bean Veggie Burger',
		cost: 16.0,
		img: '',
		costString: '$16.00',
		description: 'Avocado, lettuce, tomato & garlic aioli',
		category: 'burger',
	},
	// SALAD //
	{
		name: 'Kale Ceasar Salad',
		cost: 14.00,
		img: '',
		costString: '$14.00',
		description: 'Kale leaves tossed in a creamy Caesar dressing with croutons & parmesan cheese. Add Chicken $4 - Grilled Shrimp $6 - Steak $7',
		category: 'salad',
	},
	{
		name: 'Mermaid Salad',
		cost: 20.00,
		img: '',
		costString: '$20.00',
		description: 'Pan seared sesame crusted ahi tuna served over greens & wasabi ginger soy sauce',
		category: 'salad',
	},
	// ENTREE //
	{
		name: 'Surf and Turf',
		cost: 32.00,
		img: '',
		costString: '$32.00',
		description: 'File mignon & shrimp Substitute: lobster tail $15 - Scallops - $12',
		category: 'entree',
	},
	{
		name: 'Seasonal Steak',
		cost: 24.00,
		img: '',
		costString: '$24.00',
		description: 'Marinated & Served with potatoes & vegetables',
		category: 'entree',
	},
	{
		name: 'French Dip',
		cost: 10.00,
		img: '',
		costString: '$10.00',
		description: 'Tender roast beef sandwich, dipped in au jus. Served with hand cut fries.',
		category: 'entree',
	},
	{
		name: 'Pastrami Melt',
		cost: 10.00,
		img: '',
		costString: '$10.00',
		description: 'Hot pastrami & cheese on rye bread. Served with hand cut fries.',
		category: 'entree',
	},
	{
		name: 'Reuben Sandwich',
		cost: 7.79,
		img: '',
		costString: '$7.79',
		description: 'Pastrami, with sauerkraut, Russian dressing, on rye bread. Served with hand cut fries.',
		category: 'entree',
	},
	{
		name: 'Turkey or Chicken Club',
		cost: 14.0,
		img: '',
		costString: '$14.00',
		description: '(traditional or wrap) with bacon, lettuce, tomato, mayo',
		category: 'entree',
	},
	{
		name: 'BLT',
		cost: 8.50,
		img: '',
		costString: '$8.5',
		description: 'Classic bacon, lettuce, tomato sandwich. w/avocado $1.50',
		category: 'entree',
	},
]