module.exports = {
	permanentMakeup: [
		{
			id: 'pm-cb',
			type: 'Permanent Makeup',
			name: 'Combination Brow',
			price: 550,
			downPayment: 110,
		},
		{
			id: 'pm-ob',
			type: 'Permanent Makeup',
			name: 'Ombre Brow',
			price: 500,
			downPayment: 100,
		},
		{
			id: 'pm-m',
			type: 'Permanent Makeup',
			name: 'Microblading',
			price: 500,
			downPayment: 100,
		},
		{
			id: 'pm-ele',
			type: 'Permanent Makeup',
			name: 'Eyeline lash Enhancement',
			price: 400,
			downPayment: 80,
		},
		{
			id: 'pm-e',
			type: 'Permanent Makeup',
			name: 'Eyeliner',
			price: 400,
			downPayment: 80,
		},
		{
			id: 'pm-flc',
			type: 'Permanent Makeup',
			name: 'Full Lip Color',
			price: 550,
			downPayment: 110,
		},
		{
			id: 'pm-ll',
			type: 'Permanent Makeup',
			name: 'Lip Liner',
			price: 400,
			downPayment: 80,
		},
		{
			id: 'pm-bm',
			type: 'Permanent Makeup',
			name: 'Beauty Mark',
			price: 150,
			downPayment: 30,
		},
		{
			id: 'pm-f',
			type: 'Permanent Makeup',
			name: 'Freckles',
			price: 200,
			downPayment: 40,
		},
	],

	bestSellers: [
		{
			title: 'Classic/Natural',
			types: [
				{
					id: 'bs-cn-1',
					type: 'Best Sellers Classic/Natural',
					name: 'Week 1',
					price: 48,
					downPayment: 9.6,
				},
				{
					id: 'bs-cn-2',
					type: 'Best Sellers Classic/Natural',
					name: 'Week 2',
					price: 78,
					downPayment: 15.6,
				},
				{
					id: 'bs-cn-3',
					type: 'Best Sellers Classic/Natural',
					name: 'Week 3',
					price: 86,
					downPayment: 17.2,
				},
				{
					id: 'bs-cn-4',
					type: 'Best Sellers Classic/Natural',
					name: 'Week 4 (Full Set)',
					price: 145,
					downPayment: 29,
				},
			],
		},
		{
			title: 'Hybrid',
			types: [
				{
					id: 'bs-h-1',
					type: 'Best Sellers Hybrid',
					name: 'Week 1',
					price: 54,
					downPayment: 10.8,
				},
				{
					id: 'bs-h-2',
					type: 'Best Sellers Hybrid',
					name: 'Week 2',
					price: 89,
					downPayment: 17.8,
				},
				{
					id: 'bs-h-3',
					type: 'Best Sellers Hybrid',
					name: 'Week 3',
					price: 96,
					downPayment: 19.2,
				},
				{
					id: 'bs-h-4',
					type: 'Best Sellers Hybrid',
					name: 'Week 4 (Full Set)',
					price: 160,
					downPayment: 32,
				},
			],
		},
		{
			title: 'Volume',
			types: [
				{
					id: 'bs-v-2',
					type: 'Best Sellers Volume',
					name: 'Week 2',
					price: 100,
					downPayment: 20,
				},
				{
					id: 'bs-v-3',
					type: 'Best Sellers Volume',
					name: 'Week 3',
					price: 139,
					downPayment: 27.8,
				},
				{
					id: 'bs-v-4',
					type: 'Best Sellers Volume',
					name: 'Week 4 (Full Set)',
					price: 175,
					downPayment: 35,
				},
			],
		},
		{
			title: 'Mega Volume',
			types: [
				{
					id: 'bs-mv-2',
					type: 'Best Sellers Mega Volume',
					name: 'Week 2',
					price: 135,
					downPayment: 27,
				},
				{
					id: 'bs-mv-3',
					type: 'Best Sellers Mega Volume',
					name: 'Week 3',
					price: 155,
					downPayment: 31,
				},
				{
					id: 'bs-mv-4',
					type: 'Best Sellers Mega Volume',
					name: 'Week 4 (Full Set)',
					price: 199,
					downPayment: 39.8,
				},
			],
		},
	],

	spa: [
		{
			id: 's-tw',
			type: 'Spa',
			name: 'Teeth Whitening',
			price: 300,
			downPayment: 60,
		},
		{
			id: 's-bm',
			type: 'Spa',
			name: 'Basic Makeup',
			price: 100,
			downPayment: 20,
		},
		{
			id: 's-gm',
			type: 'Spa',
			name: 'Glam Makeup',
			price: 120,
			downPayment: 24,
		},
		{
			id: 's-3mf',
			type: 'Spa',
			name: '30 Minute Facial',
			price: 60,
			downPayment: 12,
		},
		{
			id: 's-6mf',
			type: 'Spa',
			name: '60 Minute Facial',
			price: 90,
			downPayment: 18,
		},
		{
			id: 's-hf',
			type: 'Spa',
			name: 'High Frequency',
			price: 90,
			downPayment: 18,
		},
		{
			id: 's-lcp',
			type: 'Spa',
			name: 'Luxury Chemical Peel',
			price: 110,
			downPayment: 22,
		},
		{
			id: 's-cf',
			type: 'Spa',
			name: 'Chest Facial',
			price: 60,
			downPayment: 12,
		},
		{
			id: 's-bf',
			type: 'Spa',
			name: 'Back Facial',
			price: 120,
			downPayment: 24,
		},
		{
			id: 's-ff',
			type: 'Spa',
			name: 'Fancy Facial',
			price: 95,
			downPayment: 19,
		},
	],
}